export const fixedCats = [
    {
        "breeds": [
            {
                "weight": {
                    "imperial": "6 - 12",
                    "metric": "3 - 7"
                },
                "id": "beng",
                "name": "Bengal",
                "cfa_url": "http://cfa.org/Breeds/BreedsAB/Bengal.aspx",
                "vetstreet_url": "http://www.vetstreet.com/cats/bengal",
                "vcahospitals_url": "https://vcahospitals.com/know-your-pet/cat-breeds/bengal",
                "temperament": "Alert, Agile, Energetic, Demanding, Intelligent",
                "origin": "United States",
                "country_codes": "US",
                "country_code": "US",
                "description": "Bengals are a lot of fun to live with, but they're definitely not the cat for everyone, or for first-time cat owners. Extremely intelligent, curious and active, they demand a lot of interaction and woe betide the owner who doesn't provide it.",
                "life_span": "12 - 15",
                "indoor": 0,
                "lap": 0,
                "adaptability": 5,
                "affection_level": 5,
                "child_friendly": 4,
                "cat_friendly": 4,
                "dog_friendly": 5,
                "energy_level": 5,
                "grooming": 1,
                "health_issues": 3,
                "intelligence": 5,
                "shedding_level": 3,
                "social_needs": 5,
                "stranger_friendly": 3,
                "vocalisation": 5,
                "bidability": 3,
                "experimental": 0,
                "hairless": 0,
                "natural": 0,
                "rare": 0,
                "rex": 0,
                "suppressed_tail": 0,
                "short_legs": 0,
                "wikipedia_url": "https://en.wikipedia.org/wiki/Bengal_(cat)",
                "hypoallergenic": 1,
                "reference_image_id": "O3btzLlsO"
            }
        ],
        "id": "8RsP7Xt3h",
        "url": "https://cdn2.thecatapi.com/images/8RsP7Xt3h.jpg",
        "width": 1024,
        "height": 817
    },
    {
        "breeds": [
            {
                "weight": {
                    "imperial": "6 - 15",
                    "metric": "3 - 7"
                },
                "id": "birm",
                "name": "Birman",
                "cfa_url": "http://cfa.org/Breeds/BreedsAB/Birman.aspx",
                "vetstreet_url": "http://www.vetstreet.com/cats/birman",
                "vcahospitals_url": "https://vcahospitals.com/know-your-pet/cat-breeds/birman",
                "temperament": "Affectionate, Active, Gentle, Social",
                "origin": "France",
                "country_codes": "FR",
                "country_code": "FR",
                "description": "The Birman is a docile, quiet cat who loves people and will follow them from room to room. Expect the Birman to want to be involved in what you’re doing. He communicates in a soft voice, mainly to remind you that perhaps it’s time for dinner or maybe for a nice cuddle on the sofa. He enjoys being held and will relax in your arms like a furry baby.",
                "life_span": "14 - 15",
                "indoor": 0,
                "lap": 1,
                "alt_names": "Sacred Birman, Sacred Cat Of Burma",
                "adaptability": 5,
                "affection_level": 5,
                "child_friendly": 4,
                "dog_friendly": 5,
                "energy_level": 3,
                "grooming": 2,
                "health_issues": 1,
                "intelligence": 3,
                "shedding_level": 3,
                "social_needs": 4,
                "stranger_friendly": 3,
                "vocalisation": 1,
                "experimental": 0,
                "hairless": 0,
                "natural": 0,
                "rare": 0,
                "rex": 0,
                "suppressed_tail": 0,
                "short_legs": 0,
                "wikipedia_url": "https://en.wikipedia.org/wiki/Birman",
                "hypoallergenic": 0,
                "reference_image_id": "HOrX5gwLS"
            }
        ],
        "id": "Dm0H1zSK1",
        "url": "https://cdn2.thecatapi.com/images/Dm0H1zSK1.jpg",
        "width": 1024,
        "height": 768
    },
    {
        "breeds": [
            {
                "weight": {
                    "imperial": "6 - 11",
                    "metric": "3 - 5"
                },
                "id": "bomb",
                "name": "Bombay",
                "cfa_url": "http://cfa.org/Breeds/BreedsAB/Bombay.aspx",
                "vetstreet_url": "http://www.vetstreet.com/cats/bombay",
                "vcahospitals_url": "https://vcahospitals.com/know-your-pet/cat-breeds/bombay",
                "temperament": "Affectionate, Dependent, Gentle, Intelligent, Playful",
                "origin": "United States",
                "country_codes": "US",
                "country_code": "US",
                "description": "The the golden eyes and the shiny black coa of the Bopmbay is absolutely striking. Likely to bond most with one family member, the Bombay will follow you from room to room and will almost always have something to say about what you are doing, loving attention and to be carried around, often on his caregiver's shoulder.",
                "life_span": "12 - 16",
                "indoor": 0,
                "lap": 1,
                "alt_names": "Small black Panther",
                "adaptability": 5,
                "affection_level": 5,
                "child_friendly": 4,
                "dog_friendly": 5,
                "energy_level": 3,
                "grooming": 1,
                "health_issues": 3,
                "intelligence": 5,
                "shedding_level": 3,
                "social_needs": 4,
                "stranger_friendly": 4,
                "vocalisation": 5,
                "experimental": 0,
                "hairless": 0,
                "natural": 0,
                "rare": 0,
                "rex": 0,
                "suppressed_tail": 0,
                "short_legs": 0,
                "wikipedia_url": "https://en.wikipedia.org/wiki/Bombay_(cat)",
                "hypoallergenic": 0,
                "reference_image_id": "5iYq9NmT1"
            }
        ],
        "id": "5iYq9NmT1",
        "url": "https://cdn2.thecatapi.com/images/5iYq9NmT1.jpg",
        "width": 1250,
        "height": 650
    },
    {
        "breeds": [
            {
                "weight": {
                    "imperial": "7 - 14",
                    "metric": "3 - 6"
                },
                "id": "esho",
                "name": "Exotic Shorthair",
                "cfa_url": "http://cfa.org/Breeds/BreedsCJ/Exotic.aspx",
                "vetstreet_url": "http://www.vetstreet.com/cats/exotic-shorthair",
                "vcahospitals_url": "https://vcahospitals.com/know-your-pet/cat-breeds/exotic-shorthair",
                "temperament": "Affectionate, Sweet, Loyal, Quiet, Peaceful",
                "origin": "United States",
                "country_codes": "US",
                "country_code": "US",
                "description": "The Exotic Shorthair is a gentle friendly cat that has the same personality as the Persian. They love having fun, don’t mind the company of other cats and dogs, also love to curl up for a sleep in a safe place. Exotics love their own people, but around strangers they are cautious at first. Given time, they usually warm up to visitors.",
                "life_span": "12 - 15",
                "indoor": 0,
                "lap": 1,
                "alt_names": "Exotic",
                "adaptability": 5,
                "affection_level": 5,
                "child_friendly": 3,
                "dog_friendly": 3,
                "energy_level": 3,
                "grooming": 2,
                "health_issues": 3,
                "intelligence": 3,
                "shedding_level": 2,
                "social_needs": 4,
                "stranger_friendly": 2,
                "vocalisation": 1,
                "experimental": 0,
                "hairless": 0,
                "natural": 0,
                "rare": 0,
                "rex": 0,
                "suppressed_tail": 0,
                "short_legs": 0,
                "wikipedia_url": "https://en.wikipedia.org/wiki/Exotic_Shorthair",
                "hypoallergenic": 0,
                "reference_image_id": "YnPrYEmfe"
            }
        ],
        "id": "4qG-5FC0J",
        "url": "https://cdn2.thecatapi.com/images/4qG-5FC0J.jpg",
        "width": 1689,
        "height": 1017
    },
    {
        "breeds": [
            {
                "weight": {
                    "imperial": "5 - 9",
                    "metric": "2 - 4"
                },
                "id": "munc",
                "name": "Munchkin",
                "vetstreet_url": "http://www.vetstreet.com/cats/munchkin",
                "temperament": "Agile, Easy Going, Intelligent, Playful",
                "origin": "United States",
                "country_codes": "US",
                "country_code": "US",
                "description": "The Munchkin is an outgoing cat who enjoys being handled. She has lots of energy and is faster and more agile than she looks. The shortness of their legs does not seem to interfere with their running and leaping abilities.",
                "life_span": "10 - 15",
                "indoor": 0,
                "lap": 1,
                "alt_names": "",
                "adaptability": 5,
                "affection_level": 5,
                "child_friendly": 4,
                "dog_friendly": 5,
                "energy_level": 4,
                "grooming": 2,
                "health_issues": 3,
                "intelligence": 5,
                "shedding_level": 3,
                "social_needs": 5,
                "stranger_friendly": 5,
                "vocalisation": 3,
                "experimental": 0,
                "hairless": 0,
                "natural": 0,
                "rare": 0,
                "rex": 0,
                "suppressed_tail": 0,
                "short_legs": 1,
                "wikipedia_url": "https://en.wikipedia.org/wiki/Munchkin_(cat)",
                "hypoallergenic": 0,
                "reference_image_id": "j5cVSqLer"
            }
        ],
        "id": "wBbqm3pJa",
        "url": "https://cdn2.thecatapi.com/images/wBbqm3pJa.jpg",
        "width": 225,
        "height": 225
    },
    {
        "breeds": [
            {
                "weight": {
                    "imperial": "8 - 16",
                    "metric": "4 - 7"
                },
                "id": "norw",
                "name": "Norwegian Forest Cat",
                "cfa_url": "http://cfa.org/Breeds/BreedsKthruR/NorwegianForestCat.aspx",
                "vetstreet_url": "http://www.vetstreet.com/cats/norwegian-forest-cat",
                "vcahospitals_url": "https://vcahospitals.com/know-your-pet/cat-breeds/norwegian-forest-cat",
                "temperament": "Sweet, Active, Intelligent, Social, Playful, Lively, Curious",
                "origin": "Norway",
                "country_codes": "NO",
                "country_code": "NO",
                "description": "The Norwegian Forest Cat is a sweet, loving cat. She appreciates praise and loves to interact with her parent. She makes a loving companion and bonds with her parents once she accepts them for her own. She is still a hunter at heart. She loves to chase toys as if they are real. She is territorial and patrols several times each day to make certain that all is fine.",
                "life_span": "12 - 16",
                "indoor": 0,
                "alt_names": "Skogkatt / Skaukatt, Norsk Skogkatt / Norsk Skaukatt, Weegie",
                "adaptability": 5,
                "affection_level": 5,
                "child_friendly": 4,
                "dog_friendly": 5,
                "energy_level": 3,
                "grooming": 2,
                "health_issues": 3,
                "intelligence": 4,
                "shedding_level": 3,
                "social_needs": 5,
                "stranger_friendly": 5,
                "vocalisation": 1,
                "experimental": 0,
                "hairless": 0,
                "natural": 1,
                "rare": 0,
                "rex": 0,
                "suppressed_tail": 0,
                "short_legs": 0,
                "wikipedia_url": "https://en.wikipedia.org/wiki/Norwegian_Forest_Cat",
                "hypoallergenic": 0,
                "reference_image_id": "06dgGmEOV"
            }
        ],
        "id": "-ZBBqoWNQ",
        "url": "https://cdn2.thecatapi.com/images/-ZBBqoWNQ.jpg",
        "width": 3264,
        "height": 2448
    },
    {
        "breeds": [
            {
                "weight": {
                    "imperial": "8 - 16",
                    "metric": "4 - 7"
                },
                "id": "norw",
                "name": "Norwegian Forest Cat",
                "cfa_url": "http://cfa.org/Breeds/BreedsKthruR/NorwegianForestCat.aspx",
                "vetstreet_url": "http://www.vetstreet.com/cats/norwegian-forest-cat",
                "vcahospitals_url": "https://vcahospitals.com/know-your-pet/cat-breeds/norwegian-forest-cat",
                "temperament": "Sweet, Active, Intelligent, Social, Playful, Lively, Curious",
                "origin": "Norway",
                "country_codes": "NO",
                "country_code": "NO",
                "description": "The Norwegian Forest Cat is a sweet, loving cat. She appreciates praise and loves to interact with her parent. She makes a loving companion and bonds with her parents once she accepts them for her own. She is still a hunter at heart. She loves to chase toys as if they are real. She is territorial and patrols several times each day to make certain that all is fine.",
                "life_span": "12 - 16",
                "indoor": 0,
                "alt_names": "Skogkatt / Skaukatt, Norsk Skogkatt / Norsk Skaukatt, Weegie",
                "adaptability": 5,
                "affection_level": 5,
                "child_friendly": 4,
                "dog_friendly": 5,
                "energy_level": 3,
                "grooming": 2,
                "health_issues": 3,
                "intelligence": 4,
                "shedding_level": 3,
                "social_needs": 5,
                "stranger_friendly": 5,
                "vocalisation": 1,
                "experimental": 0,
                "hairless": 0,
                "natural": 1,
                "rare": 0,
                "rex": 0,
                "suppressed_tail": 0,
                "short_legs": 0,
                "wikipedia_url": "https://en.wikipedia.org/wiki/Norwegian_Forest_Cat",
                "hypoallergenic": 0,
                "reference_image_id": "06dgGmEOV"
            }
        ],
        "id": "3Xe_cTMsx",
        "url": "https://cdn2.thecatapi.com/images/3Xe_cTMsx.jpg",
        "width": 1110,
        "height": 741
    },
    {
        "breeds": [
            {
                "weight": {
                    "imperial": "4 - 9",
                    "metric": "2 - 4"
                },
                "id": "bamb",
                "name": "Bambino",
                "temperament": "Affectionate, Lively, Friendly, Intelligent",
                "origin": "United States",
                "country_codes": "US",
                "country_code": "US",
                "description": "The Bambino is a breed of cat that was created as a cross between the Sphynx and the Munchkin breeds. The Bambino cat has short legs, large upright ears, and is usually hairless. They love to be handled and cuddled up on the laps of their family members.",
                "life_span": "12 - 14",
                "indoor": 0,
                "lap": 1,
                "alt_names": "",
                "adaptability": 5,
                "affection_level": 5,
                "child_friendly": 4,
                "dog_friendly": 5,
                "energy_level": 5,
                "grooming": 1,
                "health_issues": 1,
                "intelligence": 5,
                "shedding_level": 1,
                "social_needs": 3,
                "stranger_friendly": 3,
                "vocalisation": 3,
                "experimental": 1,
                "hairless": 1,
                "natural": 0,
                "rare": 0,
                "rex": 0,
                "suppressed_tail": 0,
                "short_legs": 1,
                "wikipedia_url": "https://en.wikipedia.org/wiki/Bambino_cat",
                "hypoallergenic": 0,
                "reference_image_id": "5AdhMjeEu"
            }
        ],
        "id": "MizM7dBMU",
        "url": "https://cdn2.thecatapi.com/images/MizM7dBMU.jpg",
        "width": 1200,
        "height": 800
    },
    {
        "breeds": [
            {
                "weight": {
                    "imperial": "7 - 12",
                    "metric": "3 - 5"
                },
                "id": "ctif",
                "name": "Chantilly-Tiffany",
                "temperament": "Affectionate, Demanding, Interactive, Loyal",
                "origin": "United States",
                "country_codes": "US",
                "country_code": "US",
                "description": "The Chantilly is a devoted companion and prefers company to being left alone. While the Chantilly is not demanding, she will \"chirp\" and \"talk\" as if having a conversation. This breed is affectionate, with a sweet temperament. It can stay still for extended periods, happily lounging in the lap of its loved one. This quality makes the Tiffany an ideal traveling companion, and an ideal house companion for senior citizens and the physically handicapped.",
                "life_span": "14 - 16",
                "indoor": 0,
                "lap": 1,
                "alt_names": "Chantilly, Foreign Longhair",
                "adaptability": 5,
                "affection_level": 5,
                "child_friendly": 4,
                "dog_friendly": 5,
                "energy_level": 4,
                "grooming": 5,
                "health_issues": 1,
                "intelligence": 5,
                "shedding_level": 5,
                "social_needs": 3,
                "stranger_friendly": 4,
                "vocalisation": 5,
                "experimental": 0,
                "hairless": 0,
                "natural": 0,
                "rare": 0,
                "rex": 0,
                "suppressed_tail": 0,
                "short_legs": 0,
                "wikipedia_url": "https://en.wikipedia.org/wiki/Chantilly-Tiffany",
                "hypoallergenic": 0,
                "reference_image_id": "TR-5nAd_S"
            }
        ],
        "id": "E4j4aBDx9",
        "url": "https://cdn2.thecatapi.com/images/E4j4aBDx9.jpg",
        "width": 2368,
        "height": 1590
    },
    {
        "breeds": [
            {
                "weight": {
                    "imperial": "6 - 16",
                    "metric": "3 - 7"
                },
                "id": "srex",
                "name": "Selkirk Rex",
                "cfa_url": "http://cfa.org/Breeds/BreedsSthruT/SelkirkRex.aspx",
                "vetstreet_url": "http://www.vetstreet.com/cats/selkirk-rex",
                "vcahospitals_url": "https://vcahospitals.com/know-your-pet/cat-breeds/selkirk-rex",
                "temperament": "Active, Affectionate, Dependent, Gentle, Patient, Playful, Quiet, Social",
                "origin": "United States",
                "country_codes": "US",
                "country_code": "US",
                "description": "The Selkirk Rex is an incredibly patient, loving, and tolerant breed. The Selkirk also has a silly side and is sometimes described as clownish. She loves being a lap cat and will be happy to chat with you in a quiet voice if you talk to her. ",
                "life_span": "14 - 15",
                "indoor": 0,
                "lap": 1,
                "alt_names": "Shepherd Cat",
                "adaptability": 5,
                "affection_level": 5,
                "child_friendly": 4,
                "dog_friendly": 5,
                "energy_level": 3,
                "grooming": 2,
                "health_issues": 4,
                "intelligence": 3,
                "shedding_level": 1,
                "social_needs": 3,
                "stranger_friendly": 3,
                "vocalisation": 3,
                "experimental": 0,
                "hairless": 0,
                "natural": 0,
                "rare": 0,
                "rex": 1,
                "suppressed_tail": 0,
                "short_legs": 0,
                "wikipedia_url": "https://en.wikipedia.org/wiki/Selkirk_Rex",
                "hypoallergenic": 1,
                "reference_image_id": "II9dOZmrw"
            }
        ],
        "id": "B2YB13Ydq",
        "url": "https://cdn2.thecatapi.com/images/B2YB13Ydq.jpg",
        "width": 3447,
        "height": 2290
    }
]  